controlPlane:
  distro:
   k8s:
     enabled: true
     image:
       registry: ghcr.io
       repository: "loft-sh/kubernetes"
       tag: "v1.32.1"
  backingStore:
    etcd:
      deploy:
        enabled: true
        statefulSet:
          persistence:
            volumeClaim:
              enabled: true
              storageClass: "managed-nfs-storage"
              size: 5Gi
  statefulSet:
    persistence:
      volumeClaim:
        storageClass: "managed-nfs-storage"
        size: 5Gi
  ingress:
    enabled: true
    host: vc1.kryukov.local
  proxy:
    extraSANs:
    - vc1.kryukov.local
    # - 192.168.218.180
exportKubeConfig:
  context: "vc1"
  server: https://vc1.kryukov.local
integrations:
  metricsServer:
    enabled: true
    nodes: true
    pods: true
sync:
  toHost:
    ingresses:
      enabled: true
policies:
  resourceQuota:
    enabled: true
    quota:
      cpu: "4"
      memory: "5Gi"
      limits.memory: "5Gi"
      pods: "15"
      requests.storage: "20Gi"
  limitRange:
    enabled: true
    default:
      memory: 512Mi
      cpu: "1"
    defaultRequest:
      memory: 128Mi
      cpu: 100m
